export const skillsData = (isMobile: boolean) => [
  {
    name: "HTML",
    top: isMobile ? "30px" : "100px",
    left: isMobile ? "-20px" : "-100px",
    fontSize: isMobile ? "2.5em" : "4em",
  },
  {
    name: "CSS",
    top: isMobile ? "60px" : "166px",
    left: isMobile ? "285px" : "600px",
    fontSize: isMobile ? "2.5em" : "3.1em",
    fromRight: true,
  },
  {
    name: "JavaScript",
    top: isMobile ? "210px" : "300px",
    left: isMobile ? "0px" : "-150px",
    fontSize: isMobile ? "3.5em" : "4.5em",
  },
  {
    name: "React",
    top: isMobile ? "290px" : "550px",
    left: isMobile ? "160px" : "400px",
    fontSize: isMobile ? "5em" : "8em",
    fromRight: true,
  },
  {
    name: "Redux",
    top: isMobile ? "130px" : "770px",
    left: isMobile ? "-15px" : "-280px",
    fontSize: isMobile ? "3em" : "3.8em",
  },
  {
    name: "Node.js",
    top: isMobile ? "350px" : "200px",
    left: isMobile ? "0px" : "-350px",
    fontSize: isMobile ? "2.5em" : "3em",
  },
  {
    name: "Express",
    top: isMobile ? "460px" : "900px",
    left: isMobile ? "190px" : "700px",
    fontSize: isMobile ? "2.3em" : "4em",
    fromRight: true,
  },
  {
    name: "Sass",
    top: isMobile ? "500px" : "1000px",
    left: isMobile ? "0px" : "-190px",
    fontSize: isMobile ? "4em" : "5.5em",
    fromRight: true,
  },
  {
    name: "React Router",
    top: isMobile ? "600px" : "1100px",
    left: isMobile ? "70px" : "250px",
    fontSize: isMobile ? "2em" : "3em",
  },
  {
    name: "Git",
    top: isMobile ? "525px" : "1320px",
    left: isMobile ? "200px" : "650px",
    fontSize: isMobile ? "4em" : "7em",
    fromRight: true,
  },
  {
    name: "TypeScript",
    top: isMobile ? "700px" : "570px",
    left: isMobile ? "30px" : "-400px",
    fontSize: isMobile ? "3.5em" : "4em",
  },
  {
    name: "Vite",
    top: isMobile ? "660px" : "870px",
    left: isMobile ? "0px" : "250px",
    fontSize: isMobile ? "1.7em" : "4em",
  },
  {
    name: "React Spring",
    top: isMobile ? "635px" : "370px",
    left: isMobile ? "145px" : "300px",
    fontSize: isMobile ? "2.2em" : "3.5em",
    fromRight: true,
  },
  {
    name: "WebSockets",
    top: isMobile ? "5px" : "1300px",
    left: isMobile ? "110px" : "-350px",
    fontSize: isMobile ? "2.4em" : "4em",
  },
];
